<div class="p-1">
    <p class="guide-purpose mb-4">Use Abuse Reports for malware, phishing, scam uploads, and other clearly harmful or policy-violating content that needs moderation rather than a copyright workflow.</p>

    <h6 class="fw-bold text-dark border-bottom pb-2 mb-3">How To Handle Abuse</h6>
    <ol class="guide-steps mb-4">
        <li><strong>Read the report carefully:</strong> Confirm what the reporter claims, which file is involved, and whether the complaint is about malware, phishing, or another TOS problem.</li>
        <li><strong>Open the file record:</strong> Check <a href="/admin/files" class="guide-action-link">Files</a> to confirm owner, server, upload date, and whether the file is already disabled or queued for removal.</li>
        <li><strong>Act quickly on dangerous content:</strong> Malware, credential theft, and obvious scam payloads should be deleted immediately instead of waiting for a longer discussion.</li>
        <li><strong>Review the uploader account:</strong> If the same user is a repeat offender, suspend or ban them from <a href="/admin/users" class="guide-action-link">Users</a> before more content appears.</li>
        <li><strong>Keep the moderation trail:</strong> Use the report, file record, and user history together so repeated patterns are visible to future admins.</li>
    </ol>

    <h6 class="fw-bold text-dark border-bottom pb-2 mb-3">What Counts As Abuse Here</h6>
    <ul class="extra-small text-muted mb-4">
        <li class="mb-2"><strong>Malware or infected archives:</strong> Anything that can compromise a visitor device or account.</li>
        <li class="mb-2"><strong>Phishing or impersonation kits:</strong> Fake login pages, wallet theft, invoice scams, and account-harvesting pages.</li>
        <li class="mb-2"><strong>General TOS violations:</strong> Spam payloads, scam packages, or other prohibited content that is not a DMCA matter.</li>
        <li><strong>Not for copyright claims:</strong> If the complaint is really about ownership or copyright, move it into <a href="/admin/dmca" class="guide-action-link">DMCA</a> so the legal record stays separate.</li>
    </ul>

    <h6 class="fw-bold text-dark border-bottom pb-2 mb-3">Common Pitfalls</h6>
    <ul class="extra-small text-muted mb-4">
        <li class="mb-2"><strong>Automated reports exist:</strong> Some reports can be generated by scanners, so always verify the file and uploader before taking account-level action.</li>
        <li class="mb-2"><strong>Dead links happen:</strong> If the content is already gone, check whether another admin handled it or cleanup already purged it.</li>
        <li><strong>Do not investigate unsafely:</strong> Never open suspicious files on your own workstation just to confirm an abuse report.</li>
    </ul>

    <div class="alert alert-danger border-0 shadow-sm small">
        <strong>Safety Guard:</strong> Treat this page as a moderation queue, not a testing sandbox. Use controlled server-side inspection only when you truly need to analyze suspicious content.
    </div>
</div>
