<div class="p-1">
    <p class="guide-purpose mb-4">Monitor and remove malicious content like malware, phishing, or TOS violations to keep your users safe.</p>

    <h6 class="fw-bold text-dark border-bottom pb-2 mb-3">How to Handle Abuse:</h6>
    <ol class="guide-steps mb-4">
        <li>
            <strong>Analyze the Report:</strong> Review the reporter's message and IP address. Look for patterns of frequent reporting for the same user.
        </li>
        <li>
            <strong>Investigate the File:</strong> Check the file name and type. Use 
            <a href="/admin/files" class="guide-action-link">File Management</a> to see if the uploader is a repeat offender.
        </li>
        <li>
            <strong>Remove Malware:</strong> If the file is dangerous, delete it immediately. Our system will also purge it from the 
            <a href="/admin/configuration?tab=storage" class="guide-action-link">Storage Nodes</a>.
        </li>
        <li>
            <strong>Sanitize the User:</strong> If a user is repeatedly uploading abuse, navigate to 
            <a href="/admin/users" class="guide-action-link">User Management</a> and suspend their account.
        </li>
    </ol>

    <h6 class="fw-bold text-dark small text-uppercase mb-2">Common Pitfalls:</h6>
    <ul class="extra-small text-muted mb-4">
        <li class="mb-2"><strong>Automation:</strong> Some reports are generated by 3rd party security scanners we integrate with.</li>
        <li><strong>Dead Links:</strong> If you can't see the file, it was likely deleted by the uploader or our auto-cleanup cron.</li>
    </ul>

    <div class="alert alert-danger border-0 shadow-sm small">
        <strong>Safety Guard:</strong> Do not download or execute files reported for Malware on your local machine. Use server-side tools only.
    </div>
</div>
